{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "daemon" },
    {
     "expr": "jvm_threads_current - jvm_threads_daemon",
     "legendFormat": "current-daemon"
    }
   ]
  },
  {
   "title": "Heap History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Eden)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Eden Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Survivor)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Survivor Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Old)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Old Gen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "net_minecraft_server_Server_averageTickTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "net_minecraft_server_Server_averageTickTime",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}