apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - dashboard.yaml
helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 75.4.0
    valuesInline:
      # This needs to be set in order to internally query the Prometheus instance.
      namespaceOverride: monitoring
      crds:
        enabled: true
        upgradeJob:
          enabled: true
      grafana:
        enabled: true
        operator:
          matchLabels:
            dashboards: grafana
        defaultDashboardsTimezone: browser
      nodeExporter:
        operatingSystems:
          aix:
            enabled: false
          darwin:
            enabled: false
      sidecar:
        dashboard:
          label: grafanaDashboard
        datasource:
          label: grafanaDatasource

